[theme]
primaryColor = "#E694FF"
backgroundColor = "#00172B"
secondaryBackgroundColor = "#0083B8"
textColor = "#FFFFFF"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
